In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x=np.array([25,35,45,55,65,75])
y=np.array([5,20,14,32,22,38])

In [3]:
print(x)

[25 35 45 55 65 75]


In [4]:
print(y)

[ 5 20 14 32 22 38]


In [5]:
x=x.reshape((-1,1))

In [6]:
print(x)

[[25]
 [35]
 [45]
 [55]
 [65]
 [75]]


In [7]:
x.shape

(6, 1)

In [8]:
model=LinearRegression()

In [9]:
model.fit(x,y)

LinearRegression()

In [10]:
r_sq_score=model.score(x,y)

In [11]:
print(r_sq_score)

0.7158756137479542


In [12]:
print(model.intercept_)

-5.166666666666668


In [13]:
print(model.coef_)

[0.54]


In [14]:
y_pred=model.predict(x)

In [15]:
print(y_pred)

[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
